language: ruby

rvm:
  - 2.1
  - 2.2
  - 2.3.3
  - ruby-head
  - jruby-head
#  - rbx-2

sudo: false

addons:
  apt:
    packages:
    - libgmp3-dev

matrix:
  allow_failures:
    - rvm: jruby-head

install:
  - gem install rainbow -v 2.2.1
  - bundle install

script: "bundle exec rake"

notifications:
  disable: true
